# Generated by Django 3.2.25 on 2025-02-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20250205_1449'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='commons.pays'),
            preserve_default=False,
        ),
    ]
