# Generated by Django 4.0.5 on 2025-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250116_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='date_expiration',
            field=models.CharField(max_length=10),
        ),
    ]
