# Generated by Django 4.0.5 on 2025-01-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_moyenpaiement_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyenpaiement',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='date_expiration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='moyenpaiement',
            name='numero_carte',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
