# Generated by Django 4.0.5 on 2025-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_moyenpaiement_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('PLATEFORME', 'PLATEFORME'), ('USER', 'USER')], default='USER', max_length=10),
        ),
    ]
