# Generated by Django 3.2.25 on 2025-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pays',
            old_name='intitule',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='pays',
            name='code_reference',
        ),
        migrations.AddField(
            model_name='pays',
            name='country_code',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pays',
            name='digit_code',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pays',
            name='iso_code2',
            field=models.CharField(default='Te', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pays',
            name='iso_code3',
            field=models.CharField(default='Te', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pays',
            name='label_en',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
