# Generated by Django 3.2.25 on 2025-01-16 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_depart', models.DateTimeField()),
                ('provenance', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('agence_voyage', models.CharField(max_length=100)),
                ('code_reservation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_publie', models.BooleanField(default=False)),
                ('type_bagage_auto', models.CharField(max_length=100)),
                ('nombre_kg_dispo', models.IntegerField()),
                ('montant_par_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_transporteur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=50)),
                ('est_actif', models.BooleanField(default=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annonces.voyage')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
    ]
