# Generated by Django 3.2.25 on 2025-01-29 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_compte', to='users.compte'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_reservation', to='annonces.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_annonce', to='annonces.annonce'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_bagage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_bagage', to='commons.typebagage'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.reservation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type_bagage_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_bagage', to='commons.typebagage'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='voyage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annonces.voyage'),
        ),
    ]
