# Generated by Django 4.0.5 on 2025-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_alter_annonce_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='revenue_transporteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
