# Generated by Django 3.2.25 on 2025-01-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_auto_20250129_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='reservation',
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_reservation', to='annonces.reservation'),
        ),
    ]
