# Generated by Django 3.2.25 on 2025-01-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_auto_20250129_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('CANCEL', 'CANCEL')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSITE', 'DEPOSITE'), ('WITHDRAWAL', 'WITHDRAWAL'), ('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], default='', max_length=12),
        ),
    ]
