# Generated by Django 3.2.25 on 2025-01-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_auto_20250129_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='type_bagage',
        ),
    ]
