# Generated by Django 3.2.25 on 2025-01-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_remove_reservation_type_bagage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typebagagereservation',
            name='annonce',
        ),
        migrations.AddField(
            model_name='typebagagereservation',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bagage_reservations', to='annonces.reservation'),
            preserve_default=False,
        ),
    ]
