# Generated by Django 3.2.25 on 2025-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0009_auto_20250129_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='moyen_transport',
            field=models.CharField(choices=[('AERIEN', 'AERIEN'), ('FERROVIAIRE', 'FERROVIAIRE'), ('ROUTIER', 'ROUTIER'), ('MARITIME', 'MARITIME')], default='', max_length=100),
        ),
    ]
