# Generated by Django 3.2.25 on 2025-01-16 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_kg', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=100)),
                ('nom_personne_a_contacter', models.CharField(max_length=100)),
                ('telephone_personne_a_contacter', models.CharField(max_length=20)),
                ('code_livraison', models.CharField(max_length=50, unique=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date_paiement', models.DateTimeField(null=True)),
                ('statut', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRM', 'CONFIRM'), ('CANCEL', 'CANCEL'), ('DELIVRATE', 'DELIVRATE')], default='PENDING', max_length=100)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='annonces.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=50)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
