# Generated by Django 4.0.5 on 2025-01-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code_livraison',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
