name: Deploy to Production

on:
  push:
    branches:
      - master  # ou main selon votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Configurer SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.36.163.57 >> ~/.ssh/known_hosts

      # Étape 3: Déployer sur le VPS
      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no guy001@54.36.163.57 << 'EOF'
            # Supprimer l'ancienne version
            sudo rm -rf /var/www/travel

            # Cloner la nouvelle version du dépôt
            cd /var/www
            git clone https://github.com/messi657816954/travel.git

            # Redémarrer Apache
            sudo systemctl restart apache2
          EOF
