name: Deploy to VPS

on:
  push:
    branches:
      - master  # Déclenche le déploiement lorsqu'il y a un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.36.163.57 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          echo "Connecting to the server..."
          sshpass -p 'Guy@vps123' ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no guy001@54.36.163.57 << 'EOF'
            echo "Removing old version..."
            sudo -S rm -rf /var/www/travel <<< 'Guy@vps123'
            echo "Cloning new version..."
            sudo git clone https://github.com/messi657816954/travel.git /var/www/travel
            echo "New version cloned"
            echo "Restarting Apache..."
            sudo -S systemctl restart apache2 <<< 'Guy@vps123'
            echo "Deployment complete!"
          EOF
