name: Deploy to VPS

on:
  push:
    branches:
      - master  # Branche principale à surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.36.163.57 >> ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no guy001@54.36.163.57 << 'EOF'
          set -e
          echo "Stopping Apache..."
          sudo systemctl stop apache2
          echo "Removing old application..."
          sudo rm -rf /var/www/travel
          echo "Cloning new application..."
          sudo git clone https://https://github.com/messi657816954/travel.git /var/www/travel
          echo "Setting permissions..."
          sudo chown -R www-data:www-data /var/www/travel
          sudo chmod -R 755 /var/www/travel
          echo "Restarting Apache..."
          sudo systemctl start apache2
          EOF
